import path from 'node:path'; import { describe, expect, test } from 'vitest';
import { analyzeImpact, createCodeownersResolver, createMigrationPlan, createSnapshot, diffSnapshots, stableStringify } from '../src/index.js';
const fixtures = path.resolve(import.meta.dirname, 'fixtures');
async function snapshots() { const common = { packageName: '@acme/ui', entry: 'src/index.ts', tokenPatterns: ['src/**/*.json', 'src/**/*.css'] }; return { before: await createSnapshot({ ...common, root: path.join(fixtures, 'v1'), packageVersion: '1.0.0' }), after: await createSnapshot({ ...common, root: path.join(fixtures, 'v2'), packageVersion: '2.0.0' }) }; }
describe('vertical migration flow', () => {
  test('extracts stable component and token contracts', async () => { const { before } = await snapshots(); expect(before.components.Button?.props.tone?.literals).toEqual(['critical', 'default']); expect(before.components.MemoButton?.props.emphasis?.literals).toEqual(['high', 'low']); expect(before.components.RefButton?.props.label?.required).toBe(true); expect(before.components.RefButton?.props.ref).toBeUndefined(); expect(before.tokens['color.danger']?.value).toBe('#cc0000'); expect(before.tokens['--color-alias']?.alias).toBe('--color-danger'); expect(stableStringify(before)).toBe(stableStringify(await createSnapshot({ root: path.join(fixtures, 'v1'), packageName: '@acme/ui', packageVersion: '1.0.0', entry: 'src/index.ts', tokenPatterns: ['src/**/*.json', 'src/**/*.css'] }))); });
  test('classifies changes without inventing a rename', async () => { const { before, after } = await snapshots(); const diff = diffSnapshots(before, after); expect(diff.changes.some((c) => c.id === 'component.Button.prop.tone.removed')).toBe(true); expect(diff.changes.some((c) => c.id === 'component.Button.prop.variant.added')).toBe(true); expect(diff.changes.some((c) => c.id === 'component.Button.prop.size.requiredness')).toBe(true); expect(diff.changes.some((c) => c.id === 'component.Button.prop.size.union-expanded')).toBe(true); expect(diff.changes.some((c) => c.changeType === 'removed' && c.category === 'component')).toBe(true); expect(diff.changes.some((c) => c.id.includes('rename'))).toBe(false); });
  test('discovers subpath additions and classifies path moves', async () => { const { before, after } = await snapshots(); expect(after.exports).toEqual(expect.arrayContaining([expect.objectContaining({ name: 'Button', importPath: '@acme/ui/button' })])); const additions = diffSnapshots(before, after); expect(additions.changes).toEqual(expect.arrayContaining([expect.objectContaining({ category: 'export', changeType: 'added', after: '@acme/ui/button' }), expect.objectContaining({ id: 'component.Button.prop.size.deprecated', changeType: 'deprecated' })])); const moved = structuredClone(after); moved.exports = moved.exports.filter((item) => item.name !== 'Button' || item.importPath === '@acme/ui/button'); const pathDiff = diffSnapshots(before, moved); expect(pathDiff.changes).toEqual(expect.arrayContaining([expect.objectContaining({ id: 'export.Button.path', changeType: 'path-changed', severity: 'breaking' })])); });
  test('finds usage, ownership, workspace, and creates only evidence-backed automatic work', async () => { const { before, after } = await snapshots(); const diff = diffSnapshots(before, after); const root = path.join(fixtures, 'consumer'); const ownership = await createCodeownersResolver(path.join(root, 'CODEOWNERS')); const report = await analyzeImpact({ root, consumers: ['apps'], packageName: '@acme/ui', diff, ownership }); const propImpact = report.impacts.find((i) => i.subject === 'Button.tone'); expect(propImpact?.observedValue).toBe('critical'); expect(propImpact?.location.owner).toEqual(['@checkout-team', '@design-systems']); expect(propImpact?.location.workspace).toBe('@acme/checkout'); expect(report.impacts.some((i) => i.changeId.endsWith('union-expanded'))).toBe(false); expect(report.impacts.some((i) => i.changeId.endsWith('requiredness') && i.location.file.endsWith('SpreadButton.tsx'))).toBe(false); expect(report.diagnostics).toEqual(expect.arrayContaining([expect.objectContaining({ code: 'DSI2101', location: expect.objectContaining({ file: 'apps/checkout/src/SpreadButton.tsx' }) })])); expect(report.impacts.some((i) => i.subject === '--color-alias')).toBe(true); const plan = createMigrationPlan(diff, report, { schemaVersion: 1, componentProps: { Button: { tone: { replacedBy: 'variant', values: { critical: 'danger' } } } }, tokens: { '--color-alias': { replacedBy: '--color-danger' } } }); const task = plan.tasks.find((t) => t.replacement?.to.includes('variant')); expect(task?.automatic).toBe(true); expect(task?.instruction).toContain('replace literal value "critical" with "danger"'); expect(plan.tasks.find((t) => t.replacement?.from === '--color-alias')?.automatic).toBe(true); });
});
describe('graceful failures', () => { test('reports malformed token JSON as a diagnostic', async () => { const temp = path.join(fixtures, 'malformed'); const snapshot = await createSnapshot({ root: temp, packageName: '@bad/ui', entry: 'index.ts', tokenPatterns: ['tokens.json'] }); expect(snapshot.diagnostics).toEqual(expect.arrayContaining([expect.objectContaining({ code: 'DSI1201', severity: 'error' })])); }); });
